### ISSUE TITLE
Issue run in to after installing all requirements

### ISSUE THREAD

**Issue by SpaceGuildIntern** [Nijmegen-Consultancy-Group/arkprofitcalculator#2]
python gen_reports.py
Traceback (most recent call last):
  File "gen_reports.py", line 19, in <module>
    main()
  File "gen_reports.py", line 14, in main
    payoutprofitcalculator.gen_payout_report()
  File "/home/ark/arkprofitcalculator/payoutprofitcalculator.py", line 30, in gen_payout_report
    balance_history = arkdb.Address.balance_over_time(address)
  File "/usr/local/lib/python2.7/dist-packages/arkdbtools/dbtools.py", line 332, in balance_over_time
    txhistory = Address.transactions(address)
  File "/usr/local/lib/python2.7/dist-packages/arkdbtools/dbtools.py", line 243, in transactions
    qry = DbCursor().execute_and_fetchall("""
  File "/usr/local/lib/python2.7/dist-packages/arkdbtools/dbtools.py", line 116, in __init__
    dbconnection = DbConnection()
  File "/usr/local/lib/python2.7/dist-packages/arkdbtools/dbtools.py", line 107, in __init__
    raise e
psycopg2.OperationalError: fe_sendauth: no password supplied

**Comment by KaiserKarel** [comment]
What user did you set for your ark-node database? If you followed these lines in the arkdbtools guide:

```sh
sudo -u postgres psql 
    psql=# ALTER USER <username> WITH ENCRYPTED PASSWORD '<password>'
```
then your credentials should be entered in the config.py 

```python
CONNECTION = {
    'HOST': 'localhost',
    'DATABASE': 'ark_mainnet',
    # The 2 lines below need to be edited if you created a user to query the ark-node
    'USER': 'ark',
    'PASSWORD': None,
}
```

Also it seems like you are using python 2.7. I am not sure if this works in that version. I personally use python 3.6. 
For different projects I always suggest using virtual environments. Anaconda is a great tool for this, especially since you can create environments in different python versions: https://conda.io/docs/user-guide/install/index.html
